### PR TITLE
Add "@" to the start of single line .cmd files

### PR DESCRIPTION
**Pull request by SkyLined**
To prevent the command from being echoed to the console, add a "@" to the start of the line.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
Would you like to be added as a collaborator on this project, to help review and merge pull requests?

**Comment by SkyLined** [comment]
Sure - though I cannot promise I can commit much time. But I don't believe this project has a lot of code changes, does it?

**Comment by ForbesLindesay** [comment]
It has very few, but I'm ill placed to review most of them since I use a mac and am not particularly well versed in bash etc.

You're added. Please follow these rules:

1. never commit directly to master unless you're only editing documentation, or you're in the process of cutting a new release.
2. never merge your own pull request unless it's had no comments from any collaborators for at least 24 hours.
3. If you cut a new release, make sure you follow [semver](http://semver.org/) when updating the version number.

If you let me know your npm username I'll add you as an owner so you can release new versions :)

**Comment by SkyLined** [comment]
Great. My npm username is skylined.

**Pull request merged**
